config/routes.rb
Rails.application.routes.draw do

  mount Attachinary::Engine => "/attachinary"

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'pages#home'

  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  as :user do
    get 'users/edit', to: 'devise/registrations#edit', as: :user_root
  end
  resources :users, only: [:show, :destroy]
  resources :equipment_sets, only: [:new, :create, :edit, :update, :destroy]

  resources :divesites do
    get :search, :on => :collection
    resources :events, shallow: true do
      resources :participations, only: [:create, :new, :update, :destroy]
    end
  end

  resources :dives do
    resources :buddies
    resources :sightings, only: [:create, :update, :destroy]
    resources :data_points, only: [:create]
  end

  resources :charts, only: [] do
    collection do
      get 'sporters_by_age'
    end
  end
end

app/views/shared/_badge.html.erb
<!-- User badge: replace "logo.png" with user picture -->
<!-- Add link_to user page when routes are created -->
<div class="badge-container">
  <%= link_to "#" do %>
    <%= image_tag "logo.png", class: "avatar" %>
  <% end %>
  <div class="badge badge-red">
    3
  </div>

  <!-- Icon badge: replace fontawesome envelope with chosen icon -->
  <!-- Add link_to correct page when routes are created -->
  <div class="badge-container">
    <%= link_to "#" do %>
    <i class="fa fa-envelope-o"></i>
  <% end %>
  <div class="badge badge-red">
    3
  </div>
</div>

app/views/shared/_banner.html.erb
<div class="banner banner-home">
  <div class="banner-content">
    <h1>Scubalog</h1>
    <p>Track your dives, find new buddies</p>
    <% if user_signed_in? %>
      <%= link_to "Dive in", current_user, class: "btn btn-banner" %>
    <% else %>
    <div class="btn btn-banner" id="dive-in">Dive in</div>
    <% end %>
  </div>
  <div class="form-login hidden"><%= render 'devise/shared/signinform' %></div>
  <div class="form-signup hidden"><%= render 'devise/shared/signupform' %></div>
</div>

app/views/shared/_card.html.erb
<div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://trello-backgrounds.s3.amazonaws.com/583060c9989f19549238eb5b/800x534/bf4ef26fa227f1b81263e4b0fef2a7ac/cenote.jpg');">
  <div class="card-category">
    Scubalog
  </div>
  <div class="card-description">
    <h2>Scubalog</h2>
    <p>Scubalog Scubalog Scubalog Scubalog</p>
  </div>
<!-- Add link_to correct page -->
  <%=  link_to "#" do %>
    <%= image_tag "logo.png", class: "card-user avatar" %>
  <% end %>

app/views/shared/_flashes.html.erb
<% if flash[:notice] %>
    <div class="alert alert-info fade in">
      <button class="close" data-dismiss="alert">×</button>
      <%= flash[:notice] %>
    </div>
  <% end %>

  <% if flash[:alert] %>
    <div class="alert alert-warning fade in">
      <button class="close" data-dismiss="alert">×</button>
      <%= flash[:alert] %>
    </div>
  <% end %>

app/views/shared/_footer.html.erb
<div class="blue-wrapper footer flex-c-center">
  <div class="container-fluid">
    <div class="row">
      <div class="footer-content flex-c-center">
        <div class="col-xs-6 col-sm-4">
          <% icons = {
            youtube: { fa: 'fa-youtube', url: "#" },
            instagram: { fa: 'fa-instagram', url: "#" },
            facebook: { fa: 'fa-facebook', url: "#" },
            twitter: { fa: 'fa-twitter', url: "#" },
            github: { fa: 'fa-github', url: "#" }
            } %>
            <% icons.each do |k, v| %>
            <div class="col-xs-<%= 12 / icons.length %>">
              <%= link_to v[:url], target: "_blank" do %>
              <i class="footer-icon fa <%= v[:fa] %> fa-2x" aria-hidden="true"></i>
              <% end %>
            </div>
            <% end %>
          </div>
          <div class="col-xs-6 col-sm-8">
            <div class="">
              <div class="hidden-sm col-md-6 credits">
              </div>
              <div class="col-xs-12 col-md-6 signature">
                <span class="footer-mail"></span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/shared/_map.js.erb
$(document).ready(function() {

  var handler = Gmaps.build('Google');
  handler.buildMap({
    provider: {
      scrollwheel: false,
      styles: myStyle
    },
    internal: { id: 'map' }
  },
  function() {
    markers = handler.addMarkers(<%= raw @hash.to_json %>);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    if (markers.length == 0) {
      handler.getMap().setZoom(2);
    } else if (markers.length == 1) {
      handler.getMap().setZoom(10); // Set map zoom here
    }
  });
});

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-fixed">
  <!-- Logo -->
    <%= link_to root_path, class: "navbar-wagon-brand" do %>
      <h3 class="font-yellowtail">Scubalog</h3>
    <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
<!--     <form action="/divesites" class="divesites-search  navbar-wagon-search ">
      <input type="text" class="navbar-wagon-search-input" placeholder="Look for a spot" name="search_input" id="divesites-search-txt">
      <button type="submit" class="results navbar-wagon-search-btn" id="divesites-search-results">
        <i class="fa fa-search"></i>
      </button>
    </form> -->

    <%= content_for :script do %>
      new app.Divesites;
    <% end %>

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Profile picture and dropdown -->
      <% avatar_url = current_user&.facebook_picture_url || "http://passeportperformances.fr/wp-content/uploads/2016/03/avatar.jpg" %>
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= display_avatar(current_user) %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to current_user do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to dives_path do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "My Dives") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <div class="navbar-wagon-item navbar-wagon-link" id="login">Login</div>
      <div class="navbar-wagon-item navbar-wagon-link" id="signup">Signup</div>
<!--       <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link", data: { toggle: "modal", target: "#modal-login" }  %>
      <%= link_to t(".sign_up", default: "Sign up"),new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link", data: { toggle: "modal", target: "#modal-login" } %> -->

    <% end %>

    <!-- Button (call-to-action) -->
    <%= link_to t(".top_call_to_action", default: "Log a Dive"), new_dive_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <% if user_signed_in? %>
  <!-- Dropdown list appearing on mobile only -->
    <div class="navbar-wagon-item hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to "Profile", current_user %>
          </li>
          <li>
            <%= link_to "My dives", dives_path %>
          </li>
          <li>
            <%= link_to t(".top_call_to_action", default: "Log a Dive"), new_dive_path %>
          </li>
          <li>
            <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
          </li>
        </ul>
      </div>
    </div>
  <% else %>
        <div class="navbar-wagon-item hidden-md hidden-lg">
      <div class="dropdown">
        <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to t(".sign_in", default: "Login"), new_user_session_path %>
          </li>
          <li>
            <%= link_to t(".sign_up", default: "Sign up"),new_user_registration_path %>
          </li>
        </ul>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_select2.js.erb
$(document).ready(function() {
  var data = [
    { id: 0, text: 'enhancement' },
    { id: 1, text: 'bug' },
    { id: 2, text: 'duplicate' },
    { id: 3, text: 'invalid' },
    { id: 4, text: 'wontfix' }
  ];
  var divesite = <%= Divesite.search_json.to_json.html_safe %>
  var divetypes = <%= Dive.types_json.to_json.html_safe %>
  $(".js-example-basic-multiple").select2({
    placeholder: "Select a type",
    data: divetypes
  });
  $(".js-example-basic-single").select2({
    placeholder: "Select a divesite",
    data: divesite,
    allowClear: true
  });

  $("dive-new-select-divesite").select2({
    placeholder: "Select a divesite",
    data: divesite,
    allowClear: true
  });
  $(".js-example-basic-multiple").select2({
    placeholder: "Select a state",
    data: divetypes
  });
});

app/views/shared/_sidebar.html.erb
<% unless current_user.blank? -%>
<div class="sidebar closed" id="sidebar">
  <div class="sidebar-content">
    <%= link_to root_path, class: "sidebar-scubalog" do %>
    <h3 class="font-yellowtail sidebar-scubalog">Scubalog</h3>
    <% end %>

    <div class="sidebar-group-user">
      <div class="sidebar-item sidebar-user-avatar">
        <%= link_to current_user do %>
          <%= display_avatar(current_user, "avatar-big") %>
        <% end %>
      </div>
      <div class="sidebar-item-name sidebar-user-name">
        <%= link_to edit_user_registration_path do %>
        <%= current_user.first_name.capitalize %> <%= current_user.last_name.capitalize %>
        <% end %>
      </div>
    </div>
    <div class="sidebar-group-actions">
      <div class="sidebar-item" style="width: 80%;">
        <%= link_to new_dive_path, class: "sidebar-link btn btn-banner-sidebar" do %>
          <span class="button-text">Log a dive</span>
        <% end %>
      </div>
    </div>
    <hr>
    <div class="sidebar-item sidebar-logo">
      <div class="sidebar-item sidebar-search">
        <form action="/divesites" class="divesites-search navbar-wagon-search">
          <input type="text" class="navbar-wagon-search-input" placeholder="  Look for a spot" name="search_input" id="divesites-search-txt">
          <button type="submit" class="results navbar-wagon-search-btn" id="divesites-search-results">
            <i class="fa fa-search"></i>
          </button>
        </form>
      </div>
    </div>

    <hr>
    <div class="sidebar-group-menus">
      <div class="sidebar-item sidebar-dashboard">
        <%= link_to "Dashboard", current_user, class: "sidebar-link" %>
      </div>
      <div class="sidebar-item sidebar-my-dives">
        <%= link_to "Dives", dives_path, class: "sidebar-link" %>
      </div>
      <div class="sidebar-item sidebar-dive-spots">
        <%= link_to "Dive spots", divesites_path, class: "sidebar-link" %>
      </div>
      <div class="sidebar-item sidebar-dive-spots">
        <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "sidebar-link" %>
      </div>
      <div class="sidebar-icons">
        <% icons = {
          github: { fa: 'fa-github', url: "https://github.com/jooleeanh/scubalog" }
          } %>
          <% icons.each do |k, v| %>
          <div class="col-xs-<%= 12 / icons.length %>">
            <%= link_to v[:url], target: "_blank" do %>
            <i class="footer-icon fa-lg <%= v[:fa] %> fa" aria-hidden="true"></i>
            <% end %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <% end %>

  <%= content_for :script do %>
  new app.Divesites;
  <% end %>

app/views/shared/_sightings.html.erb
<div class="sightings-list">
  <div class="container-fluid sightings-container">
  <h2 class="text-center">Encountered at <%= @divesite.name%> </h2>
  <hr>
    <% if sightings != nil && splitted_animals != nil %>
      <div class="row">
        <div class="col-xs-12 col-md-6 animal-box">
          <% splitted_animals[0].each do |animal| %>
          <div class="animal-card">
            <p class="text-center"><%= animal.name %></p>
            <%=  image_tag(asset_path(animal.image_url), class: "animal-image")%>
            <hr>
          </div>
          <% end %>
        </div>
        <% if splitted_animals[1] != nil %>
          <div class="col-xs-12 col-md-6 animal-box">
            <% splitted_animals[1].each do |animal| %>
              <div class="animal-card">
                <p class="text-center"><%= animal.name %></p>
                <%=  image_tag(asset_path(animal.image_url), class: "animal-image")%>
                <hr>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    <% else %>
    <p>No animal sightings reported yet</p>
    <% end %>
  </div>
</div>

app/views/shared/_signup.html.erb
<%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
<%= f.error_notification %>
<div class="container-fluid login">
  <div class="text-center">
    <hr>
      <%- if devise_mapping.omniauthable? %>
      <%- resource_class.omniauth_providers.each do |provider| %>
      <%= link_to omniauth_authorize_path(resource_name, provider), class: "btn btn-facebook" do %>
        <span class="fa fa-facebook"></span>
        Sign up with <%= OmniAuth::Utils.camelize(provider) %>
        <% end %>
        <br />
        <% end -%>
      <% end -%>
      <hr>
      <p>Or in 20sec with email</p>
      <div class="container-fluid login-form">
      <div class="form-inputs">
        <%= f.input :first_name, required: true, autofocus: true %>
        <%= f.input :location, required: true, autofocus: true %>
        <%= f.input :last_name, required: true, autofocus: true %>
        <%= f.input :email, required: true, autofocus: true %>
        <%= f.input :password, required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length) %>
        <%= f.input :password_confirmation, required: true %>
      </div>

      <div class="form-actions">
        <%= f.button :submit, "Sign up" %>
      </div>
      </div>
      <% end %>
      <div>
    <hr>
      <p>Already a member? </p>
      <%= link_to "Log in", new_session_path(resource_name), class: "btn btn-default" %><br />
    </div>
    <hr>
  </div>
</div>