config/routes.rb
Rails.application.routes.draw do

  mount Attachinary::Engine => "/attachinary"

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root to: 'pages#home'

  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  as :user do
    get 'users/edit', to: 'devise/registrations#edit', as: :user_root
  end
  resources :users, only: [:show, :destroy]
  resources :equipment_sets, only: [:new, :create, :edit, :update, :destroy]

  resources :divesites do
    get :search, :on => :collection
    resources :events, shallow: true do
      resources :participations, only: [:create, :new, :update, :destroy]
    end
  end

  resources :dives do
    resources :buddies
    resources :sightings, only: [:create, :update, :destroy]
    resources :data_points, only: [:create]
  end

  resources :charts, only: [] do
    collection do
      get 'sporters_by_age'
    end
  end
end

app/models/event.rb
# TODO: "Must have divesite and datetime"

class Event < ApplicationRecord
  # TODO: set to "no locations yet" if divesite is destroyed
  belongs_to :divesite, optional: true
  has_many :participations, dependent: :destroy
  validates :divesite, presence: true, on: :create
  validates :datetime, presence: true

  scope :recent, -> { order(datetime: :asc) }
end

# Table name: events
#  id          :integer          not null, primary key
#  divesite_id :integer
#  datetime    :datetime

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :find_event, only: [:show, :edit, :destroy]
  before_action :find_divesite, only: [:create, :update, :index, :edit, :destroy]

  def index
    @event = Event.all
    @event.each do |event|
      if event.divesite.longitude && event.divesite.latitude
        @hash = Gmaps4rails.build_markers(event.divesite) do |divesite, marker|
          marker.lat event.divesite.latitude
          marker.lng event.divesite.longitude
          marker.picture(
          {
            "url" => "http://www.myiconfinder.com/uploads/iconsets/256-256-a5485b563efc4511e0cd8bd04ad0fe9e.png",
            "width" =>  32,
            "height" => 32
          }
          )
        end
      end
      @divesite_coordinates = { lat: event.divesite.latitude, lng: event.divesite.longitude }
    end
  end

  def show
    if @event.divesite.longitude && @event.divesite.latitude
      @hash = Gmaps4rails.build_markers(@event.divesite) do |divesite, marker|
        marker.lat @event.divesite.latitude
        marker.lng @event.divesite.longitude
      end
    end
    @alert_message = "#{@event.divesite.name}"
    @divesite_coordinates = { lat: @event.divesite.latitude, lng: @event.divesite.longitude }
  end

  def new
    @event = Event.new
    @divesites = Divesite.all
  end

  def create
    @event = @divesite.events.new(event_params)
    @event.user = current_user
    if @event.save
      redirect_to @divesite
    else
      flash[:alert] = "Your event cannot be confirmed"
      render :new
    end
  end

  def edit
  end

  def update
    @event = event.find(params[:id])
    if @event.update(event_params)
      flash[:notice] = "Event created!"
      redirect_to @user
    else
      render :new
    end
  end

  def destroy
    @event.destroy
  end

  private

  def event_params
    params.require(:event).permit(:datetime)
  end

  def find_divesite
    @divesite = Divesite.find(params[:divesite_id])
  end

  def find_event
    @event = Event.find(params[:id])
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_events_cards.html.erb
<% if event.participations.present? %>
    <div class="col-xs-12 col-md-6">
      <div class="events-card">
        <div class="event-card-index">
          <div class="product">
            <div class="product-body">
              <%= link_to event do %>
                <h3><%= event.datetime.strftime("%d %b %Y") %></h3>
                <h5>By <%= event.participations.first.user.first_name.capitalize %></h5>
                <h4><%= event.divesite.name %></h4>
            </div>
              <%= display_avatar(event.participations.first.user) %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
<% end %>

app/views/events/edit.html.erb
<h1>Events#edit</h1>
<p>Find me in app/views/events/edit.html.erb</p>

app/views/events/index.html.erb
<h2 class="text-center"> Events @ <%= @divesite.name %></h2>
<div id="map" style="width: 100%; height: 400px;"></div>

<h2 class="text-center events-index-title"> Happening soon</h2>

<div class="container-fluid block-center" id="events_list">
<hr>
  <% @divesite.events.each do |e| %>
    <%= link_to e do %>
      <h4><strong> <%= e.datetime.strftime("%A, %d, %B, %Y")%></strong></h4>
    <% end %>
    <hr>
    <% if e.participations.blank?%>
      <p>
      <strong>- Team leader:</strong>
      <%= image_tag('private_avatar.png') %> <em class='small'>This team is in private mode</em>
      </p>
    <% else %>
      <p>
        <% p = e.participations.first %>
        <%= link_to p.user do %>
          <strong>- Team leader : </strong> <%= image_tag('user_avatar.png') %>
          <%= p.user.first_name.capitalize %>
          <%= p.user.last_name.capitalize %>
        <% end %>
      </p>
   <% end %>
    <p><strong>- Starting hour : </strong> <%= e.datetime.strftime("%HH%M")%></p></li>
    <p><strong>- Description : </strong> <%= e.description%></p>

   <hr>
  <% end %>
  <div class="events-index-link-back text-center">
  <%= link_to 'Back to index', divesite_path(@divesite) %>
</div>
</div>



<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    <%= render 'shared/map.js.erb' %>
  <% end %>
<% end %>

app/views/events/new.html.erb
<div class="container-fluid login">
  <div class="text-center">
    <%= simple_form_for [@divesite, @event] do |f| %>
      <%= f.error_notification %>
      <div class="form-inputs">
        <div class="container-fluid login-form">
          <%= f.input :datetime, required: true, autofocus: true %>
          <%= f.association :divesite, collection: @divesites, as: :select %>
        </div>
        <div class="form-actions">
          <%= f.button :submit, "Create new event" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/events/show.html.erb
<div class="events-header">
  <h2 class="text-center"> Organizer :
    <% if @event.participations.blank?%>
      Private
    <% else %>
      <%= link_to @event.participations.first.user do%>
    <%= @event.participations.first.user.first_name.capitalize %> <%= @event.participations.first.user.last_name.capitalize %>
      <% end %>
    <% end %>
  </h2>
</div>

<div class="events-header-location">
  <i class="fa fa-globe" style="font-size:28px;"></i>
  <h3> Location </h3>
</div>
<div class="events-map">
  <div id="map" style="width: 100%; height: 400px;"></div>
</div>
<ul class="breadcrumb divesite-breadcrumb">
<li><%= link_to 'Home', user_path(current_user) %></li>
  <li><%= link_to 'Other events near', divesite_events_path(@event.divesite_id) %></li>
</ul>

<h2 class="text-center event-show-title"> Details</h2>

<div class="container-fluid block-center" id="event_list">

  <h4><strong> <%= @event.datetime.strftime("%A, %d, %B, %Y")%></strong></h4>
  <hr>
  <p><strong>- Full Team: </strong>
  <% @event.participations.each do |participation|%>
    <%= link_to participation.user do %>
      <%= display_avatar(participation.user) %>
      <%= participation.user.first_name.capitalize %>
    <% end%>
  <% end %>
  </p>
  <hr>
  <p><strong>- Starting hour: </strong> <%= @event.datetime.strftime("%H")%>H<%= @event.datetime.strftime("%M") %> </p></li>
  <hr>
  <p><strong>- Description: </strong> <%= @event.description %></p>
  <hr>
  <p><strong>- Divesite: </strong> <%= link_to @event.divesite.name, @event.divesite %></p>
  <hr>
  <div class="text-center">
    <% if !@event.participations.map { |participation| participation.user }.include?(current_user) %>
      <p><%= link_to 'Join this team!', event_participations_path(@event.id), method: :post, class: "btn btn-primary join-event-button center-block"%></p>
    <% else %>
      <p>You are participating to this event.</p>
      <p><%= link_to 'Cancel participation', participation_path(@event.participations.find { |participation| participation.user == current_user }), method: :delete, class: "btn btn-primary cancel-event-button center-block"%></p>
    <% end %>
  </div>
</div>

<% content_for(:after_js) do %>
  <%= javascript_tag do %>
    <%= render 'shared/map.js.erb' %>
  <% end %>
<% end %>